### ISSUE TITLE
Add Python unit tests to cover new constructs

### ISSUE THREAD

**Issue by bobdanek** [aws-samples/aws-cdk-intro-workshop#119]
### General Information

* [ ] :wave: I may be able to implement this feature request

* [ ] :warning: This feature might incur a breaking change 

### Description
After running `cdk init sample-app --language python` some very basic unit tests are created that cover the constructs in the sample app, but as the sample app is modified no tests are included to cover the additional constructs added in the later sections of the workshop. Testing is an important part of learning a new technology, and CDK should be no exception, so including some basic examples of how to test CDK constructs in Python would be helpful to users like me who learn best by example.

### Proposed Solution
Add unit tests to cover the new constructs introduced as the user progresses through the workshop.

### Environment

  - **CDK CLI Version: 1.22.0 (build 309ac1b)** 
  - **Section: Hello, CDK!, Writing constructs, Using construct libraries** 
  - **Browser: all** 
  - **Language: Python**

**Comment by wuqunfei** [comment]
CDK python is more important than CDK typescript for many organizations. Because it is not typescript good enough, but it is the legacy script and knowledge from Devops team, no one from the current DevOps is writing typescript. And in the DevOps and Data team, Python is the only choice. And AWS has already https://aws.amazon.com/sdk-for-python/, is any chance to speed up this direction, we can contribute to it.

**Comment by NGL321** [comment]
@wuqunfei thank you for the upvote! 
There presently isn't a `cdk-assert` library for python (and therefore no specific cdk content to overview), and thus the delay. However, since this has more traction, I can make sure that some basic testing gets added.

Let me know if you have any suggestions on tests to add to better cover this without a `cdk assert`!

😸 😷

**Comment by wuqunfei** [comment]
@NGL321, thanks for the response. We are facing the problem, using terraform HCL is really hard to make the unit test and end 2 end test. With high-frequency cloud version changes or terraform version changes, it is the pain. And terraform is creating Terraform CDK project. Unfortunately, it even worse than AWS CDK typescript test libraries. So we are really looking forward to contributing to it. 

I understand the demo test is using app.synth() to get stack(), then get the template(), is it same in typescript? 
`app.synth().get_stack("cdk-python").template`

Is CDK assert library only doing the JSON assert, but using same get temple logic or not? Sorry I did not have time to read the js code deeply.

**Comment by peterwoodworth** [comment]
This has been implemented!
