### ISSUE TITLE
Next button to navigate to the next section

### ISSUE THREAD

**Issue by Exter-dg** [aws-samples/aws-cdk-intro-workshop#1229]
### General Information

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

Currently, there is no `next` button to go to the next page. One has to navigate from the side bar manually to go to the next page.

### Proposed Solution

We can add a Next hyperlink similar to the `Edit this page` link at the bottom of the page.

### Browser

all

### Language

all

**Comment by ashishdhingra** [comment]
Closing this feature request in favor of https://github.com/aws-samples/aws-cdk-intro-workshop/issues/1369 which already has corresponding PR https://github.com/aws-samples/aws-cdk-intro-workshop/pull/1393. As of now, PR adds support for Next/Prev links within a section, not jumping between sections (since we wanted to come up with a generic logic, instead of hard coding anything).
