### ISSUE TITLE
Doc update on Python virtulenv section

### ISSUE THREAD

**Issue by warisfutile** [aws-samples/aws-cdk-intro-workshop#183]
### What is the problem?
Typo on first command on [Python Create Project: virtualenv](https://cdkworkshop.com/30-python/20-create-project/200-virtualenv.html). The previous command `cdk init sample-app --language python` creates a .venv, not a .env directory.

Documentation update
Current: source .env/bin/activate
Should be: source .venv/bin/activate

### Reproduction Steps
Located on https://cdkworkshop.com/30-python/20-create-project/200-virtualenv.html

### Verbose Log
NA

### Environment
NA

### Other information 
Update command reference to say .venv instead of .env

**Comment by peterwoodworth** [comment]
Huh, thanks for pointing that out @kamikazestar. I'll have to take a look and see if any of the changes made to this repo actually go through. That change was merged in November...

Upon a little bit of looking it seems like none of the changes that have happened since November 2020 have taken effect, based on looking at a handful of issues merged from recently until then. The most recent changes made in October have taken effect, so I would assume everything before that has taken effect as well.

**Comment by peterwoodworth** [comment]
Given this issue has been fixed, I will go ahead and close it. I will look into getting the workshop updated ASAP
