### ISSUE TITLE
current Python "main-workshop" code fails to deploy

### ISSUE THREAD

**Issue by gliptak** [aws-samples/aws-cdk-intro-workshop#226]
### What is the problem?

```
git clone git@github.com:aws-samples/aws-cdk-intro-workshop.git
cd aws-cdk-intro-workshop/code/python/main-workshop
$ cdk deploy
  File "app.py", line 5
    from cdk-workshop.cdk-workshop_stack import CdkWorkshopStack
            ^
SyntaxError: invalid syntax
```

### Environment

  - **CDK CLI Version:** 1.106.1 (build c832c1b)
  - **Section:** 
  - **Browser:** 
  - **Language:** Python

**Comment by ryparker** [comment]
Hey @gliptak :wave:

Thanks for bringing this to our attention and for opening a PR! It looks like you found the issue which seems to be related to using `-` in the python directories and file names.

I marked this as p2 which means we're unable to work on this immediately but since you've implemented the fix that should expedite the process. By the way here's our [contribution guidelines](https://github.com/aws/aws-cdk/blob/master/CONTRIBUTING.md) if you have any questions related to contributing.

Thanks!
