### ISSUE TITLE
[TypeScript] Add a step to let user know to install AWS SDK.

### ISSUE THREAD

**Issue by monilbid** [aws-samples/aws-cdk-intro-workshop#730]
### General Information

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

### Description

The TypeScript instructions don't explicitly tell the user to install the AWS SDK, so this request is to introduce that instruction.

### Proposed Solution

Add a one-liner on how to install the AWS SDK.

### Language

TypeScript

**Comment by peterwoodworth** [comment]
Hey @monilbid, thanks for the request. 

You don't need to install the sdk because the function won't be ran in your local environment, but rather on AWS Lambda which will have the `aws-sdk` automatically installed in the environment. Since we're not giving instructions on how to test your Lambda locally (which isn't exclusively something you'd do in CDK) I'd personally prefer we don't add this instruction

Why do you think this should be in the Workshop?

**Comment by monilbid** [comment]
Hey Peter!

Thanks for the explanation!

Having it as a dev dependency can help with intellisense. But after your explanation, I think it should be worded differently than the way I did in the PR I created.

**Comment by peterwoodworth** [comment]
You're right, I agree that it would be nice for intellisense. Perhaps we can install it just with a dev dependency like you say, that could be fine if you note it as optional and say explicitly what it's for :)
