### ISSUE TITLE
Have lambda functions in workshop use same language as the workshop itself

### ISSUE THREAD

**Issue by RomainMuller** [aws-samples/aws-cdk-intro-workshop#96]
### General Information
Currently, all lambda functions used in the workshop are authored in Javascript, but the
workshop would be more impactful if those Lambdas were written in the same language
as the infrastructure code.

**Comment by douglasnaphas** [comment]
This is especially a problem for the [TypeScript tutorial](https://cdkworkshop.com/20-typescript.html).

`cdk init` adds `*.js` files to `.gitignore`. So if you follow the tutorial and add your `lambda/hello.js` and `lambda/hitcounter.js` files, for example, and commit your work, they won't be in Git.

It's not quite as simple as changing the file extensions to `.ts`, because, in the case of `lambda/hello.js`, `lambda/hello.ts` gives a compiler error:

```
lambda/hello.ts:1:35 - error TS7006: Parameter 'event' implicitly has an 'any' type.

1 exports.handler = async function (event) {
```

I changed the offending line to

```
exports.handler = async function (event: { event: any }) {
```

to silence the error, but it would be great if the example used this opportunity to point out what the right type is for an event passed to a function handler.

**Comment by peterwoodworth** [comment]
Closing in favor of https://github.com/aws-samples/aws-cdk-intro-workshop/issues/154
